### ISSUE TITLE
Can't download the datasets

### ISSUE THREAD

**Issue by ACkuku** [BAILOOL/PlaceRecognition-LoopDetection#1]
Hi, I can't download the datasets.

**Comment by BAILOOL** [comment]
@ACkuku Thank you very much for the interest in this work. A few days ago our lab server (http://rcv.kaist.ac.kr/) has been attacked by hackers. Our security team has taken it down to eliminate the weak points. It is expected to be back in a couple of days. I will let you know once it is back. I am very sorry for the inconvenience.

**Comment by BAILOOL** [comment]
@ACkuku, Sorry for taking so long. We have expected the server to be fixed in a short amount of time, but, unfortunately, it takes unreasonably long. Meanwhile, I have created temporary links to download the dataset:
- [PlaceRecognition](http://143.248.39.254/PlaceRecognition.zip) 
- [LoopDetection](http://143.248.39.254/LoopDetection.zip)

**Comment by ACkuku** [comment]
@BAILOOL  Thank you very much!
